spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/testredisdb
    username: varc
#    password:

  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true  # change to pretty SQL text

jwt:
  secret: 1d3c5ef1bd06bb0ed5a34f316297a21c57f7ed235d4e3b2e9a0dc4b4ef3ef134
#  expiration: 86400000
